// Demo data shown when no CSV is loaded
export const SAMPLE_VACANCIES = [
  {
    id: 'NXJ-130',
    title: 'WSC Android',
    isPlan: 4,
    isFact: 0,
    newLeadCount: 847,
    newLeadLastMoved: new Date(Date.now() - 8 * 24 * 3600 * 1000).toISOString(),
    submitCount: 0,
    activeWeeks: 5,
    rawStages: { 'New Lead': 847, 'IS': 0, 'Submit': 0 },
    dataSource: ['demo'],
  },
  {
    id: 'NXJ-136',
    title: 'WSC Fullstack',
    isPlan: 3,
    isFact: 1,
    newLeadCount: 220,
    newLeadLastMoved: new Date(Date.now() - 4 * 24 * 3600 * 1000).toISOString(),
    submitCount: 1,
    activeWeeks: 2,
    rawStages: { 'New Lead': 220, 'IS': 1, 'Submit': 1 },
    dataSource: ['demo'],
  },
  {
    id: 'NXJ-137',
    title: 'WSC FS Dev',
    isPlan: 2,
    isFact: 2,
    newLeadCount: 80,
    newLeadLastMoved: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
    submitCount: 3,
    activeWeeks: 2,
    rawStages: { 'New Lead': 80, 'IS': 2, 'Submit': 3 },
    dataSource: ['demo'],
  },
  {
    id: 'NXJ-141',
    title: 'Backend Node.js',
    isPlan: 3,
    isFact: 0,
    newLeadCount: 310,
    newLeadLastMoved: new Date(Date.now() - 6 * 24 * 3600 * 1000).toISOString(),
    submitCount: 0,
    activeWeeks: 4,
    rawStages: { 'New Lead': 310, 'IS': 0, 'Submit': 0 },
    dataSource: ['demo'],
  },
  {
    id: 'NXJ-145',
    title: 'QA Automation',
    isPlan: 2,
    isFact: 3,
    newLeadCount: 45,
    newLeadLastMoved: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
    submitCount: 2,
    activeWeeks: 1,
    rawStages: { 'New Lead': 45, 'IS': 3, 'Submit': 2 },
    dataSource: ['demo'],
  },
];
